# Generated by Django 4.0.2 on 2023-07-08 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=1000)),
                ('answer', models.TextField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/', verbose_name='Изображение к заданию')),
                ('video', models.TextField(max_length=40)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathematics.exercisetype')),
            ],
        ),
    ]
