# Generated by Django 4.0.2 on 2023-07-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0002_alter_exercise_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='video',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
    ]
