# Generated by Django 4.0.2 on 2023-07-08 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseReady',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registr.profile')),
            ],
        ),
    ]
