# Generated by Django 4.0.2 on 2023-07-08 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathematics', '0004_alter_exercise_id'),
        ('registr', '0002_exerciseready'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseready',
            name='exercise_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mathematics.exercise'),
        ),
    ]
